### ISSUE TITLE
Integrate with mapbox-upload-validate

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-upload#18]
Preflight with https://github.com/mapbox/mapbox-upload-validate

**Comment by drewbo** [comment]
I'm getting:

    Error: Not Found
    at Request._callback (/Users/andrewbollinger/github-repos/landsat-mapbox-api/node_modules/mapbox-upload/index.js:65:23)
    at Request.self.callback (/Users/andrewbollinger/github-repos/landsat-mapbox-api/node_modules/mapbox-upload/node_modules/request/request.js:372:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/andrewbollinger/github-repos/landsat-mapbox-api/node_modules/mapbox-upload/node_modules/request/request.js:1317:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/andrewbollinger/github-repos/landsat-mapbox-api/node_modules/mapbox-upload/node_modules/request/request.js:1265:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)

Called from a local node server using the example code:

    var progress = upload({
    file: 'final.tif', // Path to file on disk.
    account: account, // Mapbox user account.
    accesstoken: apiToken, // A valid Mapbox API secret token with the map:write scope enabled.
    mapid: account + '.' + req.body.sceneID // The identifier of the map to create or update.
    });

Is it because my `.tif` isn't supported?

**Comment by willwhite** [comment]
This usually indicates an access control problem.

- Confirm that your access token has the `uploads:write` scope. The scope suggested in the README example was out-of-date.
- Confirm that the owner of the token and the owner of the `mapid` match.

If it's still not working can you open a new ticket or email help@mapbox.com so we can keep this issue focused on mapbox-upload-validation integration?

**Comment by mapsam** [comment]
Plans are to deprecate this repository in favor of `mapbox-cli-py`. If this feature is still desired, let's plan on opening a new ticket in that repo!

refs: https://github.com/mapbox/mapbox-cli-py/issues/83
